// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:95073ef2-e86d-439a-8a18-ae251a71744f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_wQw6lqnTp",
    "aws_user_pools_web_client_id": "24d15e1tkp62j9a6ucpld6gg1f",
    "oauth": {
        "domain": "tapstrrestaurants-tapstrenv.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://restaurants.tapstr.io/login/",
        "redirectSignOut": "https://restaurants.tapstr.io/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
